README.md, info.json, src/todo/UI.lua, src/todo/todo.lua
Thanks to Tarrke for the input on this issue :)
=> refs #5 added sorting

.gitignore, README.md, locale/ru/locale.cfg, spec/54_button_text_feature.lua, spec/UI_spec.lua, spec/task_spec.lua, src/todo/todo.lua
I fixed the problem with the button text and added the russian translations.
@Tarrke @hoylemd @gsuberland please take a look :)
=> button text and russian

locale/nl/locale.cfg
PS Factorio modportal has notifications nowadays, so you could change the on-portal mod description
=> Add Dutch translations

README.md, info.json, locale/pl/locale.cfg, spec/81_minimize_main_frame_feature.lua, src/todo/features/main_ui.lua
=> #81 added tests and fixed polish translation

locale/pl/locale.cfg
=> Update locale.cfg pl

README.md, info.json
=> fix release version

README.md, info.json, locale/zh-CN/locale.cfg
=> added chinese translation

README.md, spec/11_subtasks_feature.lua, spec/58_delete_task_feature.lua, spec/60_show_created_by_feature.lua, src/todo/features/import_task.lua
=> closes #92 importing completed subtasks marks them as open now

.github/release.sh
=> added release script

README.md, changelog.txt, info.json
=> release 17.0.1

.github/release.sh
=> fix comparison

.github/release.sh
=> changed release script to use API. Much safer anyway

.github/release.sh
=> fix curl again

.github/release.sh
=> use repo identifier corerctly

.github/release.sh
=> create the correct version..

.github/release.sh
=> set faketorio to verbose again

changelog.txt, info.json, src/todo/todo.lua
=> Fix changelog and questmode

locale/en/default.cfg, locale/nl/default.cfg, locale/nl/quest.cfg
This merge fixes some small errors in the existing Dutch translations, and adds missing translations.
Since this is the first time I ever touched someone else's project, I'd like to make sure I'm doing this right :)
=> Add missing Dutch translations

locale/pt-br/default.cfg, locale/pt-br/quest.cfg
Hello Team, just contributing with PT-BR translation :)
=> PT-BR translation

changelog.txt, info.json
=> Release 17.3.0

changelog.txt, info.json, src/control.lua
=> Ready for 11

changelog.txt, info.json, src/control.lua
=> "Release version 19.0.2"

changelog.txt, info.json
=> "Release version 19.0.4"

changelog.txt
=> fix changelog

info.json
=> fix checkmarm

release.py
=> fix release script

locale/et/default.cfg, locale/et/quest.cfg
Add Estonian translations to the project
Also, are some strings perhaps too long for the UI?
=> Add Estonian language

.github/workflows/publish_to_factorio.yml
=> feat: allow workflow dispatch for the publish job

README.md
[Please describe what the goal of the PR is.](refactor: update project description to encourage contributions)
=> refactor: update project description to encourage contributions

.github/workflows/publish_to_factorio.yml, changelog.txt
=> chore: update changelog with base64 changes

.github/workflows/publish_to_factorio.yml, src/locale/de/default.cfg
Opening a copy of https://github.com/JonasJurczok/factorio-todo-list/pull/217 due to pipeline problems on the original PR.
=> chore: update German translation by @Lucanoria

changelog.txt, src/info.json
=> chore: update version

changelog.txt, src/control.lua, src/info.json, src/todo/todo.lua
=> Revert enter for task

.github/workflows/CI.yml, .github/workflows/Release.yml, changelog.txt, src/info.json
=> Check build rules

.github/workflows/CI.yml
=> ci: fix pre-release zip assembly
